using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Threading.Tasks;

namespace Properties_Harjo_Ryan
{
    class Car
    {
        private string model;// Private field to store the model value

        public string Model { get { return model; } set { model = value; } } // Public property to get and set the 'model' value
                                                                             // The 'get' accessor returns the value of the 'model' field
                                                                             // The 'set' accessor allows setting the value of the 'model' field      

        public string Make { get; set; }    // Public auto-implemented property for 'Make'
                                            // This automatically creates a private backing field, which is managed by C#
                                            // The 'get' and 'set' accessors are automatically generated by the compiler                

    }




}
